url: https://nedojp.github.io
baseurl: /nedojp.github.io/

# Site settings
title: NEDO Japan
email: nedobsys@gmail.com
description: "This is the offical web site for NEDO teams."


# Team names, titles and social links
people:
- name: Ramin Tadayon
  pic: 1
  position: Research collaborator
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ramin-tadayon-110240105/
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
