url: https://nedojp.github.io
baseurl: /nedojp.github.io/

# Site settings
title: NEDO Japan
email: nedobsys@gmail.com
description: "This is the offical web site for smart society for enjoying long healthy life."


# Team names, titles and social links
people:
- name: Yuichi Kurita
  pic: 1
  position: Project leader
  social:
    - title: twitter
      url: https://twitter.com/mykurita
    - title: facebook
      url: https://www.facebook.com/yuichi.kurita
    - title: linkedin
      url: https://www.linkedin.com/in/yuichi-kurita-33051265/

- name: Ramin Tadayon
  pic: 2
  position: Research collaborator at Hiroshima University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ramin-tadayon-110240105/
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #

- name: Antonio Vega
  pic: 3
  position: Research assitant at Hiroshima University
  social:
    - title: twitter
      url: https://twitter.com/SpainDice
    - title: linkedin
      url: https://www.linkedin.com/in/totovr/
    - title: blog
      url: https://totovr.github.io/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 1-4-1 Kagamiyama
  - line: Higashihiroshima, Hiroshima Prefecture, Japan 739-0046

# Build settings
markdown: kramdown
permalink: pretty
